version: '2.1'
services:
  database:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DATABASE=exampledb
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
    restart: always
    healthcheck:
      test: timeout 1 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/5432' || exit 1
      interval: 1m
      retries: 2
  webserver:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    environment:
      - NGINX_HOST=webserver
      - NGINX_PORT=80
    links:
      - database
    depends_on:
      - database
    restart: always
    healthcheck:
      test: timeout 1 bash -c 'cat < /dev/null > /dev/tcp/127.0.0.1/80' || exit 1
      interval: 1m
      retries: 2
